### ISSUE TITLE
Interested in collaborating?

### ISSUE THREAD

**Issue by progfolio** [KeyWeeUsr/emacs-syncthing#1]
I have some ideas for how this package could be rewritten to be more flexible and performant. As it stands, the package would need to be mostly re-written to achieve these goals. Do you have any interest in working on a re-write together?

**Comment by KeyWeeUsr** [comment]
Sure, why not. I kind of expect it to be rewritten anyway, especially the handling of JSON and the overall state keeping kind of into a way React forces the state to be treated as the approach it very similar with `:action` and `:notify` on parent-children widget relationships.

What do you have in mind?

**Comment by progfolio** [comment]
> Sure, why not.

Glad to hear it.

> What do you have in mind?

As you point out, the data from the server needs to be stored somewhere.
It also should be computed independently of drawing the "view" of the client.
Both of these can be solved by making use of a server struct.

Starting there will make everything else easier to implement.
Does that make sense?

I've roughed out an implementation here:

https://github.com/progfolio/emacs-syncthing/blob/rewrite/syncthing.el

**Comment by progfolio** [comment]
```emacs-lisp
(require 'widget)
(require 'wid-edit)
(require 'cl-macs)
(require 'cl-lib)
(require 'url)

(defgroup syncthing nil
  "Customization group for `syncthing'."
  :group 'external
  :group 'communication)

(cl-defstruct (syncthing-server (:copier nil) (:named nil)
                                (:constructor syncthing--server))
  "Syncthing server struct."
  name url token data)

(defun syncthing--request (method url token &rest data)
  "Return METHOD response from URL with TOKEN and DATA."
  (let ((url-request-method method)
        (url-request-data data)
        (url-request-extra-headers `(("X-Api-Key" . ,token))))
    ;;@TODO: handle error responses
    (with-temp-buffer (url-insert-file-contents url)
                      (json-parse-buffer :object-type 'alist
                                         :array-type 'list
                                         :null-object nil
                                         :false-object nil))))

(defun syncthing-request (server method endpoint &rest data)
  "Return SERVER response for METHOD at ENDPOINT for request with DATA."
  (apply #'syncthing--request
         (append (list method
                       (format "%s/%s" (syncthing-server-url server) endpoint)
                       (syncthing-server-token server))
                 data)))

(defun syncthing--server-update (server)
  "Update SERVER config data."
  (cl-loop with data = (syncthing-request server "GET" "rest/config")
           with folders = (alist-get 'folders data)
           for i below (length folders)
           for folder = (nth i folders)
           for id = (alist-get 'id folder)
           do (setf (alist-get 'completion folder)
                    (syncthing-request server "GET"
                                       (concat "rest/db/completion?folder=" id))
                    (alist-get 'status folder)
                    (syncthing-request server "GET"
                                       (concat "rest/db/status?folder=" id))
                    (nth i folders) folder)
           (cl-loop with devices = (alist-get 'devices data)
                    for i below (length devices)
                    for device = (nth i devices)
                    for device-id = (alist-get 'deviceID device)
                    for endpoint = (format "rest/db/completion?device=%s&folder=" device-id)
                    do (setf (alist-get id (alist-get 'progress device) nil nil #'equal)
                             (syncthing-request server "GET" (concat endpoint id))
                             (nth i devices) device))
           finally return (setf (syncthing-server-data server) data)))

(defun syncthing-server (name url token)
  "Return server with NAME URL and TOKEN."
  (let ((server (syncthing--server :name name :url url :token token)))
    (syncthing--server-update server)
    server))
```

**Comment by KeyWeeUsr** [comment]
@progfolio I wonder about the Common Lisp requirements, shouldn't we stick just to ELisp? And I presume the faces and the rest were removed for simplicity to showcase the rewrite, right?

Overall it looks awesome, mainly the automatic JSON parsing. I'm not that familiar with CommonLisp and as you see my ELisp knowledge is quite rusty too. I'll take a look over the weekend and if there isn't any strict blocker that would make it unavailable from let's say allowing it to work in older Emacs versions I'll implement most things from it.

Unless, of course, you want to submit a patch, but for that case please keep the faces and other `defcustom` values there :yum:

**Comment by progfolio** [comment]
> @progfolio I wonder about the Common Lisp requirements, shouldn't we stick just to ELisp? 

cl-lib is a common library. There's no real harm in using it. Of course, things can be rewritten sans its macros/functions, too.


> And I presume the faces and the rest were removed for simplicity to showcase the rewrite, right?

Yes. The style should come after the functionality, IMO. Once a solid design is there it's very easy to add some face properties to strings.


> Overall it looks awesome, mainly the automatic JSON parsing. I'm not that familiar with CommonLisp and as you see my ELisp knowledge is quite rusty too. I'll take a look over the weekend and if there isn't any strict blocker that would make it unavailable from let's say allowing it to work in older Emacs versions I'll implement most things from it.
> 
> Unless, of course, you want to submit a patch, but for that case please keep the faces and other `defcustom` values there 😋

Take a look at things and keep working at it. Let me know if you have any questions.

**Comment by KeyWeeUsr** [comment]
> cl-lib is a common library. There's no real harm in using it.

Alright, let's keep it, it looks leaner that way :+1:

**Comment by KeyWeeUsr** [comment]
Closing as most of the ideas have been implemented :tada:
